# Generated by Django 5.2 on 2025-10-01 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador'), ('DIRECTOR_CURSO', 'Director de Curso'), ('ACUDIENTE', 'Acudiente')], default='ESTUDIANTE', max_length=20)),
                ('es_director', models.BooleanField(default=False)),
                ('requiere_cambio_clave', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_maxima', models.IntegerField(default=40, verbose_name='Capacidad Máxima')),
                ('anio_escolar', models.CharField(default='2025-2026', max_length=9, verbose_name='Año Escolar')),
                ('seccion', models.CharField(default='A', max_length=100, verbose_name='Sección')),
                ('grado', models.CharField(choices=[('PREKINDER', 'Prekinder'), ('KINDER', 'Kinder'), ('JARDIN', 'Jardín'), ('TRANSICION', 'Transición'), ('1', 'Primer grado'), ('2', 'Segundo grado'), ('3', 'Tercer grado'), ('4', 'Cuarto grado'), ('5', 'Quinto grado'), ('6', 'Sexto grado'), ('7', 'Séptimo grado'), ('8', 'Octavo grado'), ('9', 'Noveno grado'), ('10', 'Décimo grado'), ('11', 'Undécimo grado')], default='6', max_length=20, verbose_name='Grado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('director', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol__in': ['DOCENTE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Director de Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['grado', 'seccion'],
                'unique_together': {('grado', 'seccion', 'anio_escolar')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='tasks.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'unique_together': {('nombre', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ActividadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Actividad de la Semana', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_semanales', to='tasks.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='tasks.materia')),
            ],
            options={
                'verbose_name': 'Actividad Semanal',
                'verbose_name_plural': 'Actividades Semanales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='tasks.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'unique_together': {('nombre', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.question')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('acudiente', models.ForeignKey(limit_choices_to={'perfil__rol': 'ACUDIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Acudiente')),
                ('estudiante', models.ForeignKey(limit_choices_to={'perfil__rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='acudientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Estudiante')),
            ],
            options={
                'verbose_name': 'Vínculo Acudiente-Estudiante',
                'verbose_name_plural': 'Vínculos Acudiente-Estudiante',
                'unique_together': {('acudiente', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.chatroom', verbose_name='Sala de Chat')),
            ],
            options={
                'verbose_name': 'Usuario Activo',
                'verbose_name_plural': 'Usuarios Activos',
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_escritos', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_recibidos', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tasks.materia')),
            ],
            options={
                'verbose_name': 'Comentario del Docente',
                'verbose_name_plural': 'Comentarios de los Docentes',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('docente', 'estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(default='2025-1', max_length=20, verbose_name='Periodo Académico')),
                ('activo', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_materias', to='tasks.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tasks.materia')),
            ],
            options={
                'verbose_name': 'Asignación de Materia',
                'verbose_name_plural': 'Asignaciones de Materias',
                'unique_together': {('materia', 'curso', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_escolar', models.CharField(default='2025-2026', max_length=9, verbose_name='Año Escolar')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculados', to='tasks.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('estudiante', 'anio_escolar')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('numero_nota', models.IntegerField(default=1, verbose_name='Número de Nota')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tasks.materia', verbose_name='Materia')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_registradas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tasks.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('estudiante', 'materia', 'periodo', 'numero_nota')},
            },
        ),
        migrations.CreateModel(
            name='LogroPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Logro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_periodo', to='tasks.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros_materia', to='tasks.materia', verbose_name='Materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='tasks.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Logro del Periodo',
                'verbose_name_plural': 'Logros de los Periodos',
                'ordering': ['periodo', '-fecha_creacion'],
                'unique_together': {('curso', 'periodo', 'docente', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Convivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor de la nota de 0.0 a 5.0', max_digits=3)),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional del director de curso', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivencias', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convivencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivencias_curso', to='tasks.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivencias_periodo', to='tasks.periodo')),
            ],
            options={
                'verbose_name': 'Nota de Convivencia',
                'verbose_name_plural': 'Notas de Convivencia',
                'ordering': ['-periodo', 'estudiante'],
                'unique_together': {('estudiante', 'curso', 'periodo')},
            },
        ),
    ]
