# Generated by Django 5.2 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='archivo_calendario',
            field=models.FileField(blank=True, null=True, upload_to='institucion/documentos/', verbose_name='Calendario Académico'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='archivo_malla_curricular',
            field=models.FileField(blank=True, null=True, upload_to='institucion/documentos/', verbose_name='Malla Curricular'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='archivo_manual_convivencia',
            field=models.FileField(blank=True, null=True, upload_to='institucion/documentos/', verbose_name='Manual de Convivencia'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='archivo_proyectos',
            field=models.FileField(blank=True, null=True, upload_to='institucion/documentos/', verbose_name='Proyectos Transversales'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='archivo_pei',
            field=models.FileField(blank=True, help_text='Carga aquí el Proyecto Educativo Institucional en formato PDF.', null=True, upload_to='institucion/documentos/', verbose_name='Documento PEI (PDF)'),
        ),
    ]
