# Generated by Django 5.2 on 2026-01-18 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_institucion_archivo_calendario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservadorArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=200)),
                ('estudiante_username', models.CharField(max_length=150)),
                ('fecha_archivado', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(upload_to='archivos/observadores_retirados/')),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observador Archivado (Retirado)',
                'verbose_name_plural': 'Observadores Archivados',
            },
        ),
    ]
