# Generated by Django 5.2 on 2026-01-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_observadorarchivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='accion',
            field=models.CharField(choices=[('mejoras_estudiante', 'mejoras_estudiante'), ('chat_socratico', 'chat_socratico'), ('mejoras_docente', 'mejoras_docente'), ('orientacion_curso', 'orientacion_curso'), ('apoyo_acudiente', 'apoyo_acudiente'), ('staff_academico', 'staff_academico'), ('analisis_convivencia', 'analisis_convivencia'), ('cumplimiento_pei', 'cumplimiento_pei'), ('analisis_global_bienestar', 'analisis_global_bienestar'), ('riesgo_academico_global', 'riesgo_academico_global')], help_text='La intención pedagógica (Intents).', max_length=50),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONVIVENCIA', 'Convivencia'), ('ACADEMICO', 'Académico'), ('PSICOLOGIA', 'Psicología')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
