# Generated by Django 5.2 on 2026-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_aiusagelog_accion_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Detalle Principal'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='tipo',
            field=models.CharField(choices=[('CONVIVENCIA', 'Convivencia'), ('ACADEMICO', 'Académico'), ('PSICOLOGIA', 'Psicología'), ('FELICITACION', 'Felicitación / Reconocimiento')], max_length=20),
        ),
    ]
