# Generated by Django 5.2 on 2025-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_periodo_academico_db_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_institucion/')),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=200, null=True)),
                ('lema', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_lectivo', models.CharField(default='2025', max_length=10)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Información Institucional',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='puede_generar_boletin',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el acudiente no podrá generar boletín desde su panel.', verbose_name='Acudiente puede generar boletín'),
        ),
    ]
