# Generated by Django 5.2 on 2026-01-26 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_seguimiento_observaciones_adicionales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='Número de Acta')),
                ('titulo', models.CharField(max_length=200, verbose_name='Asunto / Título')),
                ('tipo', models.CharField(choices=[('REUNION_AREA', 'Reunión de Área/Departamento'), ('COMITE', 'Comité de Evaluación/Convivencia'), ('SEGUIMIENTO_LABORAL', 'Seguimiento Laboral/Docente'), ('REUNION_PADRES', 'Reunión con Padres'), ('OTRO', 'Otro / General')], default='OTRO', max_length=30)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('contenido', models.TextField(verbose_name='Desarrollo de la reunión')),
                ('compromisos', models.TextField(blank=True, null=True, verbose_name='Compromisos y Tareas')),
                ('asistentes_externos', models.TextField(blank=True, help_text='Nombres de externos (separados por coma)')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actas/adjuntos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='actas_participacion', to=settings.AUTH_USER_MODEL, verbose_name='Asistentes (Sistema)')),
            ],
            options={
                'verbose_name': 'Acta Institucional',
                'verbose_name_plural': 'Actas Institucionales',
                'ordering': ['-consecutivo'],
            },
        ),
    ]
