# Generated by Django 5.2 on 2026-01-26 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_actainstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actainstitucional',
            options={'ordering': ['-consecutivo'], 'verbose_name': 'Acta Oficial', 'verbose_name_plural': 'Libro de Actas'},
        ),
        migrations.AddField(
            model_name='actainstitucional',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización'),
        ),
        migrations.AddField(
            model_name='actainstitucional',
            name='orden_dia',
            field=models.TextField(blank=True, verbose_name='Orden del Día'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='asistentes_externos',
            field=models.TextField(blank=True, help_text='Nombres completos y cargos de invitados externos.'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='compromisos',
            field=models.TextField(blank=True, null=True, verbose_name='Acuerdos y Tareas'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='consecutivo',
            field=models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='No. Acta'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='contenido',
            field=models.TextField(verbose_name='Desarrollo y Discusiones'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Secretario(a) / Elaboró'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar o Sala'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='actas_participacion', to=settings.AUTH_USER_MODEL, verbose_name='Asistentes Registrados'),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='tipo',
            field=models.CharField(choices=[('CONSEJO_DIRECTIVO', '🏛️ Consejo Directivo'), ('CONSEJO_ACADEMICO', '🎓 Consejo Académico'), ('RECTORIA', 'Despacho de Rectoría'), ('COORDINACION', 'Reunión de Coordinación'), ('COMITE_CONVIVENCIA', '⚖️ Comité de Convivencia Escolar'), ('COMISION_EVALUACION', '📊 Comisión de Evaluación y Promoción'), ('COMITE_CALIDAD', '✅ Comité de Calidad / Gestión'), ('COMITE_INCLUSION', '🌈 Comité de Inclusión'), ('REUNION_AREA', '📚 Reunión de Área / Departamento'), ('CLAUSTRO', '👥 Claustro General de Docentes'), ('JORNADA_PEDAGOGICA', '🧠 Jornada Pedagógica'), ('DESCARGOS', '⚠️ Diligencia de Descargos'), ('ACTA_COMPROMISO', '🤝 Acta de Compromiso (Académico/Convivencial)'), ('MEDIACION', '🕊️ Acta de Mediación / Conciliación'), ('SITUACION_ESPECIAL', '🚨 Protocolo de Situación Tipo II / III'), ('REUNION_PADRES', '👨\u200d👩\u200d👧\u200d👦 Reunión de Padres de Familia'), ('ASOCIACION_PADRES', 'Asociación de Padres (Asopadres)'), ('CONSEJO_ESTUDIANTIL', 'Consejo Estudiantil'), ('OTRO', '📝 Otro / General')], default='OTRO', max_length=50),
        ),
        migrations.AlterField(
            model_name='actainstitucional',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Asunto / Título Oficial'),
        ),
    ]
