# Generated by Django 5.2 on 2025-10-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_institucion_matricula_puede_generar_boletin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentariodocente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comentariodocente',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='comentariodocente',
            unique_together={('docente', 'estudiante', 'materia', 'periodo')},
        ),
    ]
