# Generated by Django 5.2 on 2025-11-04 15:24

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_comentariodocente_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(db_index=True, help_text='Nombre completo del estudiante al momento del retiro.', max_length=255)),
                ('username_estudiante', models.CharField(db_index=True, help_text='Username (documento) del estudiante para referencia.', max_length=150)),
                ('grado_archivado', models.CharField(choices=[('PREKINDER', 'Prekinder'), ('KINDER', 'Kinder'), ('JARDIN', 'Jardín'), ('TRANSICION', 'Transición'), ('1', 'Primer grado'), ('2', 'Segundo grado'), ('3', 'Tercer grado'), ('4', 'Cuarto grado'), ('5', 'Quinto grado'), ('6', 'Sexto grado'), ('7', 'Séptimo grado'), ('8', 'Octavo grado'), ('9', 'Noveno grado'), ('10', 'Décimo grado'), ('11', 'Undécimo grado')], db_index=True, help_text='El grado que cursaba el estudiante en este boletín.', max_length=20)),
                ('seccion_archivada', models.CharField(help_text="La sección (ej. 'A') que cursaba.", max_length=100)),
                ('anio_lectivo_archivado', models.CharField(db_index=True, help_text="El año escolar de este boletín (ej. '2024-2025').", max_length=9)),
                ('fecha_eliminado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó este archivo (retiro).')),
                ('archivo_pdf', models.FileField(help_text='El archivo PDF del boletín.', upload_to=tasks.models.ruta_archivo_boletin)),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Administrador que realizó el retiro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_archivados_por_mi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boletín Archivado (Exalumno)',
                'verbose_name_plural': 'Boletines Archivados (Exalumnos)',
                'ordering': ['-anio_lectivo_archivado', 'grado_archivado', 'nombre_estudiante'],
                'unique_together': {('username_estudiante', 'anio_lectivo_archivado')},
            },
        ),
    ]
