# Generated by Django 5.2 on 2026-01-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_actainstitucional_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actainstitucional',
            name='implicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_implicado', to=settings.AUTH_USER_MODEL, verbose_name='Persona Citada / Implicada'),
        ),
    ]
