# Generated by Django 5.2 on 2026-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_actainstitucional_implicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recibir_sms',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no llegarán alertas al celular.', verbose_name='Activar Notificaciones SMS'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_sms',
            field=models.CharField(blank=True, help_text='Número para notificaciones urgentes (+57...)', max_length=15, null=True, verbose_name='Celular para Alertas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_sms_enviado',
            field=models.DateTimeField(blank=True, help_text='Control de spam para no enviar mensajes repetidos el mismo día.', null=True),
        ),
    ]
