# Generated by Django 5.2 on 2025-11-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_boletinarchivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='puede_ver_observador',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el acudiente no podrá descargar el observador.', verbose_name='Acudiente puede ver Observador'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador'), ('DIRECTOR_CURSO', 'Director de Curso'), ('ACUDIENTE', 'Acudiente'), ('PSICOLOGO', 'Psicólogo'), ('COORD_CONVIVENCIA', 'Coord. Convivencia'), ('COORD_ACADEMICO', 'Coord. Académico')], default='ESTUDIANTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONVIVENCIA', 'Situación de Convivencia'), ('ACADEMICA', 'Compromiso Académico'), ('PSICOLOGIA', 'Orientación Psicológica'), ('FELICITACION', 'Felicitación / Reconocimiento')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción de la situación')),
                ('compromisos_estudiante', models.TextField(blank=True, verbose_name='Compromisos del Estudiante')),
                ('compromisos_familia', models.TextField(blank=True, verbose_name='Compromisos de la Familia/Acudiente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_limite_edicion', models.DateTimeField(editable=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='tasks.periodo')),
            ],
            options={
                'verbose_name': 'Observación del Alumno',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
