# Generated by Django 5.2 on 2025-11-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_matricula_puede_ver_observador_alter_perfil_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='institucion',
            name='archivo_pei',
            field=models.FileField(blank=True, help_text='Carga aquí el Proyecto Educativo Institucional en formato PDF.', null=True, upload_to='documentos_institucionales/', verbose_name='Documento PEI (PDF)'),
        ),
    ]
