# Generated by Django 5.2 on 2026-01-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_perfil_recibir_sms_perfil_telefono_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(blank=True, db_index=True, help_text='Cédula, TI, Pasaporte, etc.', max_length=30, null=True, verbose_name='Documento de Identidad'),
        ),
    ]
