# Generated by Django 5.2 on 2026-01-29 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_perfil_numero_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_referencia', models.CharField(db_index=True, max_length=100)),
                ('grado_referencia', models.CharField(choices=[('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Once')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('es_cognitivo', models.BooleanField(default=True, verbose_name='Saber')),
                ('es_procedimental', models.BooleanField(default=False, verbose_name='Hacer')),
                ('es_actitudinal', models.BooleanField(default=False, verbose_name='Ser')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco de Logro',
            },
        ),
        migrations.CreateModel(
            name='DefinicionNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('orden', models.PositiveIntegerField(default=1)),
                ('temas', models.TextField(blank=True, default='', help_text='Temas evaluados')),
                ('subtemas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('logros_asociados', models.ManyToManyField(blank=True, to='tasks.bancologro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_evaluacion', to='tasks.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_evaluacion', to='tasks.periodo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NotaDetallada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='tasks.definicionnota')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_notas_v2', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bancologro',
            index=models.Index(fields=['materia_referencia', 'grado_referencia'], name='tasks_banco_materia_73f4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bancologro',
            index=models.Index(fields=['titulo'], name='tasks_banco_titulo_8e5d8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='definicionnota',
            unique_together={('materia', 'periodo', 'orden')},
        ),
        migrations.AddIndex(
            model_name='notadetallada',
            index=models.Index(fields=['estudiante', 'definicion'], name='tasks_notad_estudia_240932_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notadetallada',
            unique_together={('definicion', 'estudiante')},
        ),
    ]
