# Generated by Django 5.2 on 2025-11-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_institucion_ciudad_remove_institucion_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_institucionales/'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='resolucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
