# Generated by Django 5.2 on 2026-01-30 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_bancologro_definicionnota_notadetallada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observadorarchivado',
            name='anio_lectivo_archivado',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Año Lectivo'),
        ),
        migrations.AddIndex(
            model_name='observadorarchivado',
            index=models.Index(fields=['estudiante_username', 'anio_lectivo_archivado'], name='tasks_obser_estudia_1b4323_idx'),
        ),
    ]
