# Generated by Django 5.2 on 2026-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_observadorarchivado_anio_lectivo_archivado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PEI', 'Proyecto Educativo (Misión/Visión)'), ('MANUAL', 'Manual de Convivencia (Reglas)'), ('EVALUACION', 'Sistema de Evaluación (Escala Notas)')], max_length=20, unique=True, verbose_name='Tipo de Documento')),
                ('contenido_texto', models.TextField(blank=True, help_text='Pega aquí el texto original del PDF por si necesitas consultarlo después.', verbose_name='Texto Legal Completo (Referencia)')),
                ('resumen_ia', models.TextField(help_text="Reglas RESUMIDAS y CLARAS. Ej: 'Falta leve = Retardo. Aprueba con 3.0'.", verbose_name='Instrucciones Lógicas para IA')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cerebro Institucional (IA)',
                'verbose_name_plural': 'Reglas Institucionales (IA)',
                'ordering': ['tipo'],
            },
        ),
    ]
