# Generated by Django 5.2 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_mensajeinterno_notificacion_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeinterno',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_chat/', verbose_name='Archivo Adjunto'),
        ),
    ]
