# Generated by Django 5.2 on 2026-02-09 21:35

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_institucionknowledgebase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='accion',
            field=models.CharField(choices=[('est_mejoras', 'est_mejoras'), ('est_pareto', 'est_pareto'), ('est_nivelacion', 'est_nivelacion'), ('chat_socratico', 'chat_socratico'), ('doc_grupo', 'doc_grupo'), ('doc_individual', 'doc_individual'), ('mejoras_docente', 'mejoras_docente'), ('orientacion_curso', 'orientacion_curso'), ('apoyo_acudiente', 'apoyo_acudiente'), ('staff_academico', 'staff_academico'), ('analisis_convivencia', 'analisis_convivencia'), ('cumplimiento_pei', 'cumplimiento_pei'), ('analisis_global_bienestar', 'analisis_global_bienestar'), ('riesgo_academico_global', 'riesgo_academico_global')], help_text='La intención pedagógica (Intents).', max_length=50),
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('modelo_objetivo', models.CharField(max_length=50)),
                ('nombre_columna_csv', models.CharField(max_length=255)),
                ('campo_sistema', models.CharField(max_length=100)),
                ('confianza', models.FloatField(default=1.0)),
                ('usado_veces', models.IntegerField(default=1, help_text='Peso para el algoritmo de sugerencia')),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memoria de Mapeo',
                'unique_together': {('modelo_objetivo', 'nombre_columna_csv', 'institucion_id')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_original', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_modelo', models.CharField(db_index=True, help_text="Ej: 'Estudiante', 'Profesor', 'Nota'", max_length=50)),
                ('estado', models.CharField(choices=[('PENDING', '⏳ Analizando Estructura'), ('MAPPING', '🗺️ Esperando Mapeo de Columnas'), ('STAGING', '🛡️ En Cuarentena (Validando)'), ('READY', '✅ Listo para Importar'), ('IMPORTING', '🚀 Escribiendo en Producción'), ('COMPLETED', '🏆 Finalizado con Éxito'), ('FAILED', '❌ Fallido'), ('ROLLED_BACK', '⏪ Revertido (Deshecho)')], db_index=True, default='PENDING', max_length=20)),
                ('log_errores', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_procesadas', models.IntegerField(default=0)),
                ('filas_exitosas', models.IntegerField(default=0)),
                ('filas_con_error', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='StagingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField(db_index=True)),
                ('data_original', models.JSONField(help_text='Datos crudos del Excel')),
                ('data_normalizada', models.JSONField(blank=True, help_text='Datos limpios tras pasar por DataGuard', null=True)),
                ('es_valido', models.BooleanField(db_index=True, default=False)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('id_objeto_creado', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('snapshot_backup', models.JSONField(blank=True, help_text='Copia de seguridad del registro antes de ser modificado', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_staging', to='tasks.importbatch')),
            ],
            options={
                'verbose_name': 'Fila en Staging',
                'ordering': ['numero_fila'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['usuario', 'creado_en'], name='tasks_impor_usuario_bef890_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['estado'], name='tasks_impor_estado_68b88f_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['file_hash'], name='tasks_impor_file_ha_0f895a_idx'),
        ),
    ]
