# Generated by Django 5.2 on 2025-12-11 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0013_mensajeinterno_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Identificador único para asignar por código (ej: 'primer-post')", unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gamification/badges/')),
                ('clase_css', models.CharField(choices=[('BRONZE', 'Bronce (Básico)'), ('SILVER', 'Plata (Intermedio)'), ('GOLD', 'Oro (Avanzado)'), ('DIAMOND', 'Diamante (Experto)')], default='BRONZE', max_length=20)),
                ('puntos_otorgados', models.IntegerField(default=10, help_text='Puntos de reputación que suma este logro')),
                ('es_oculto', models.BooleanField(default=False, help_text='Si es True, no aparece en la lista hasta que se gana')),
            ],
            options={
                'verbose_name': 'Definición de Logro',
                'verbose_name_plural': 'Definiciones de Logros',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/covers/', verbose_name='Foto de Portada'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez visto'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='Si es falso, solo profesores y compañeros de curso pueden verlo.'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puntos_reputacion',
            field=models.IntegerField(default=0, verbose_name='Reputación Académica'),
        ),
        migrations.AlterField(
            model_name='boletinarchivado',
            name='anio_lectivo_archivado',
            field=models.CharField(db_index=True, help_text='El año escolar de este boletín.', max_length=9),
        ),
        migrations.AlterField(
            model_name='boletinarchivado',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_archivados_por_mi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boletinarchivado',
            name='fecha_eliminado',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó este archivo.'),
        ),
        migrations.AlterField(
            model_name='boletinarchivado',
            name='grado_archivado',
            field=models.CharField(choices=[('PREKINDER', 'Prekinder'), ('KINDER', 'Kinder'), ('JARDIN', 'Jardín'), ('TRANSICION', 'Transición'), ('1', 'Primer grado'), ('2', 'Segundo grado'), ('3', 'Tercer grado'), ('4', 'Cuarto grado'), ('5', 'Quinto grado'), ('6', 'Sexto grado'), ('7', 'Séptimo grado'), ('8', 'Octavo grado'), ('9', 'Noveno grado'), ('10', 'Décimo grado'), ('11', 'Undécimo grado')], db_index=True, help_text='El grado que cursaba el estudiante.', max_length=20),
        ),
        migrations.AlterField(
            model_name='boletinarchivado',
            name='seccion_archivada',
            field=models.CharField(help_text='La sección que cursaba.', max_length=100),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Edición'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGIN_FAIL', 'Fallo de Login'), ('SENSITIVE', 'Acceso Sensible')], max_length=20)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles', models.TextField(blank=True, help_text='JSON o texto con los cambios (valores antes/después)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del grupo')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='grupos/portadas/')),
                ('tipo_privacidad', models.CharField(choices=[('PUBLICO', 'Público (Cualquiera puede unirse)'), ('PRIVADO', 'Privado (Requiere aprobación)')], default='PUBLICO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo Social',
                'verbose_name_plural': 'Grupos Sociales',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('MODERATOR', 'Moderador'), ('MEMBER', 'Miembro')], default='MEMBER', max_length=10)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupo',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='miembros',
            field=models.ManyToManyField(related_name='grupos_sociales', through='tasks.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='¿Qué estás pensando?')),
                ('tipo', models.CharField(choices=[('PUBLICACION', 'Publicación General'), ('ANUNCIO', 'Anuncio Oficial'), ('EVENTO', 'Evento')], default='PUBLICACION', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='social_feed/images/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='social_feed/files/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación Social',
                'verbose_name_plural': 'Publicaciones Sociales',
                'ordering': ['-es_destacado', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tasks.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tasks.post')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('BULLYING', 'Acoso o Intimidación'), ('HATE', 'Lenguaje de Odio'), ('SPAM', 'Spam o Contenido Basura'), ('VIOLENCE', 'Violencia o Amenazas'), ('SEXUAL', 'Contenido Sexual'), ('OTHER', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalles adicionales')),
                ('object_id', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('RESOLVED', 'Resuelto / Tomada Acción'), ('DISMISSED', 'Descartado / Falso Reporte')], default='PENDING', max_length=20)),
                ('resolucion', models.TextField(blank=True, help_text='Nota del moderador sobre la acción tomada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Moderación',
                'verbose_name_plural': 'Reportes de Moderación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-creado_en'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIKE', '👍 Me gusta'), ('LOVE', '❤️ Me encanta'), ('WOW', '😲 Me asombra'), ('SAD', '😢 Me entristece'), ('ANGRY', '😡 Me enoja')], default='LIKE', max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tasks_react_content_dddf30_idx')],
                'unique_together': {('usuario', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'ordering': ['-fecha_obtenido'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
