# Generated by Django 5.2 on 2025-12-11 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_logro_perfil_biografia_perfil_foto_perfil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logro',
            name='es_oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logro',
            name='puntos_otorgados',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='grupos/', verbose_name='Imagen de Portada')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='grupos_unidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tasks.socialgroup'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.socialgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
