# Generated by Django 5.2 on 2026-02-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_aiusagelog_accion_columnmapping_importbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.IntegerField(db_index=True)),
                ('nombre_institucion', models.CharField(default='Sistema', max_length=255)),
                ('calificaciones_json', models.JSONField(default=dict)),
                ('meta_confianza', models.JSONField(default=dict, help_text='Evidencia de los valores originales del Excel')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='tasks.perfil')),
                ('lote_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_creados', to='tasks.importbatch')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.historialacademico')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'ordering': ['-anio_lectivo', '-version'],
                'indexes': [models.Index(fields=['estudiante', 'anio_lectivo', 'is_active'], name='tasks_histo_estudia_97a137_idx')],
            },
        ),
    ]
