# Generated by Django 5.2 on 2025-12-15 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_auditlog_detalles_alter_logro_es_oculto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialgroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grupo Social', 'verbose_name_plural': 'Grupos Sociales'},
        ),
        migrations.RenameField(
            model_name='socialgroup',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='socialgroup',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='miembros',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='nombre',
        ),
        migrations.AddField(
            model_name='perfil',
            name='gustos_musicales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Música favorita'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Mis Hobbies'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='libros_favoritos',
            field=models.TextField(blank=True, null=True, verbose_name='Libros que me gustan'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='materia_favorita',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Materia favorita'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='metas_anio',
            field=models.TextField(blank=True, null=True, verbose_name='Metas del año lectivo'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL, verbose_name='Administradores'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/covers/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='¿Es público?'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='members',
            field=models.ManyToManyField(related_name='social_groups', through='tasks.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='Miembros'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='name',
            field=models.CharField(default='Grupo General', max_length=100, verbose_name='Nombre del Grupo'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='tipo_privacidad',
            field=models.CharField(choices=[('PUBLICO', 'Público (Cualquiera puede unirse)'), ('PRIVADO', 'Privado (Requiere aprobación)')], default='PUBLICO', max_length=10),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logro',
            name='slug',
            field=models.SlugField(help_text='Identificador único', unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolucion',
            field=models.TextField(blank=True, help_text='Nota del moderador'),
        ),
    ]
