# Generated by Django 5.2 on 2026-02-10 15:26

import django.core.validators
import django.db.models.deletion
import tasks.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_historialacademico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador inmutable para referencias seguras (Anti-Enumeration)', unique=True)),
                ('anio_lectivo', models.IntegerField(db_index=True, help_text='Año histórico del activo (ej: 1998)', verbose_name='Año Lectivo')),
                ('tipo', models.CharField(choices=[('OBSERVADOR', '📜 Observador / Disciplina'), ('BOLETIN', '📊 Boletín de Calificaciones'), ('ACTA', '⚖️ Acta de Comisión/Promoción'), ('CERTIFICADO', '🎓 Certificado de Estudio'), ('MATRICULA', '📝 Ficha de Matrícula'), ('PAZ_SALVO', '💰 Paz y Salvo'), ('DOCUMENTO_ID', '🆔 Documento de Identidad'), ('CLINICO', '🏥 Soporte Clínico/Médico'), ('LEGAL', '⚖️ Soporte Legal/Jurídico'), ('SOFTWARE_LEGACY', '💾 Software Educativo / Ejecutable'), ('DATA_DUMP', '🗃️ Base de Datos / Excel'), ('OTRO', '📁 Otro Documento')], db_index=True, default='OTRO', max_length=20)),
                ('archivo', models.FileField(help_text='Soporta Documentos, Imágenes, Excel y Ejecutables Legacy. Máx 100MB.', upload_to=tasks.models.documento_path_builder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'svg', 'webp', 'zip', 'rar', '7z', 'tar', 'gz', 'xlsx', 'xls', 'csv', 'json', 'xml', 'exe', 'msi'])])),
                ('nombre_original', models.CharField(help_text='Nombre original sanitizado', max_length=255)),
                ('extension', models.CharField(blank=True, editable=False, max_length=10)),
                ('peso_kb', models.PositiveIntegerField(default=0, editable=False, help_text='Peso en Kilobytes')),
                ('hash_sha256', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('procesado_automaticamente', models.BooleanField(default=False)),
                ('es_confidencial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_historicos', to='tasks.perfil')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Histórico',
                'verbose_name_plural': 'Repositorio Digital',
                'ordering': ['-anio_lectivo', 'tipo', 'nombre_original'],
                'indexes': [models.Index(fields=['estudiante', 'anio_lectivo', 'tipo'], name='tasks_docum_estudia_21bc43_idx'), models.Index(fields=['hash_sha256'], name='tasks_docum_hash_sh_f01ba5_idx')],
            },
        ),
    ]
