# Generated by Django 5.2 on 2025-12-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_socialgroup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialgroup',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='socialgroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='socialgroup',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='socialgroup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
