# Generated by Django 5.2 on 2026-02-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_documentohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historialacademico',
            unique_together={('estudiante', 'anio_lectivo', 'version')},
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='curso_snapshot',
            field=models.CharField(default='Sin Registro Historico', help_text='El curso en el que estaba al momento del cierre (ej: 601)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='estado_final',
            field=models.CharField(choices=[('PROMOVIDO', 'Promovido'), ('REPROBADO', 'Reprobado'), ('GRADUADO', 'Graduado'), ('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='promedio_final',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='puesto_ocupado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='meta_confianza',
            field=models.JSONField(default=dict, help_text='Metadatos de auditoría o valores originales'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='nombre_institucion',
            field=models.CharField(default='Sistema Stratos', max_length=255),
        ),
        migrations.CreateModel(
            name='CierreAnualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_cerrado', models.IntegerField()),
                ('anio_nuevo', models.IntegerField()),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('total_procesados', models.IntegerField(default=0)),
                ('promovidos', models.IntegerField(default=0)),
                ('reprobados', models.IntegerField(default=0)),
                ('graduados', models.IntegerField(default=0)),
                ('archivo_backup', models.FileField(blank=True, null=True, upload_to='security/backups/')),
                ('exitoso', models.BooleanField(default=False)),
                ('log_detalle', models.TextField(help_text='Traza técnica paso a paso')),
                ('ejecutado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialacademico',
            name='lote_origen',
        ),
    ]
