# Generated by Django 5.2 on 2026-02-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_historialacademico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacademico',
            name='archivo_boletin',
            field=models.FileField(blank=True, help_text='Copia digital inmutable del boletín entregado a los padres.', null=True, upload_to='historiales/boletines/%Y/'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='anio_lectivo',
            field=models.IntegerField(db_index=True, help_text='Año escolar cerrado (Ej: 2026)'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='curso_snapshot',
            field=models.CharField(help_text='Nombre del curso en el momento exacto del cierre (Ej: 601, Transición).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='estudiante',
            field=models.ForeignKey(help_text='Perfil del estudiante al momento del cierre.', on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='tasks.perfil'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='meta_confianza',
            field=models.JSONField(default=dict, help_text='Metadatos técnicos: materias perdidas, usuario que ejecutó el cierre, fecha exacta.'),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='puesto_ocupado',
            field=models.IntegerField(blank=True, help_text='Puesto en el curso según promedio.', null=True),
        ),
    ]
