# Generated by Django 5.2 on 2025-12-15 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_socialgroup_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='social_groups', to=settings.AUTH_USER_MODEL, verbose_name='Miembros'),
        ),
        migrations.AlterField(
            model_name='socialgroup',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
    ]
