# Generated by Django 5.2 on 2026-02-11 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_historialacademico_archivo_boletin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BovedaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_operacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_identificador', models.CharField(db_index=True, max_length=150)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archivo_zip', models.FileField(help_text='Paquete encriptado de activos institucionales.', upload_to='security/vault/%Y/%m/')),
                ('tamanio_mb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('checksum_sha256', models.CharField(editable=False, help_text='Firma digital única del archivo para auditorías de integridad.', max_length=64)),
                ('stats_contenido', models.JSONField(default=dict, help_text='Resumen detallado del contenido del paquete.')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Dispositivo desde donde se ordenó el respaldo.', null=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respaldos_custodiados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo de Bóveda',
                'verbose_name_plural': 'Bóveda de Seguridad Institucional',
                'ordering': ['-fecha_generacion'],
                'permissions': [('can_restore_vault', 'Puede ejecutar restauraciones desde la bóveda'), ('can_export_external', 'Puede exportar archivos fuera del servidor')],
            },
        ),
    ]
