# Generated by Django 5.2 on 2025-12-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_securitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PEIResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ej: v2025.1 - Actualización Manual Convivencia', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text="Solo una versión del PEI es la 'Verdad Absoluta' a la vez.")),
                ('contenido_estructurado', models.JSONField(default=dict, help_text='JSON estructurado con Misión, Visión, Ejes, Evaluación y Convivencia.')),
                ('comentarios_cambio', models.TextField(blank=True, help_text='Justificación de los cambios en esta versión (Auditoría).')),
            ],
            options={
                'verbose_name': 'Conocimiento PEI (JSON)',
                'verbose_name_plural': 'Versiones del PEI',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2025-1, Año Lectivo 2025, Trimestre 2', max_length=100, unique=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha oficial de inicio del periodo académico')),
                ('fecha_fin', models.DateField(help_text='Fecha oficial de finalización del periodo académico')),
                ('activo', models.BooleanField(default=False, help_text='🔴 CRÍTICO: Solo un periodo puede estar activo. Al activar este, se desactivan los demás.')),
                ('limite_intentos_profesor', models.IntegerField(default=10, help_text='Intentos de IA profunda (DeepSeek) permitidos por periodo para docentes.')),
                ('limite_intentos_estudiante', models.IntegerField(default=2, help_text='Intentos de IA profunda permitidos por periodo para estudiantes.')),
                ('limite_intentos_acudiente', models.IntegerField(default=1, help_text='Intentos de IA para orientación familiar por periodo.')),
                ('limite_intentos_staff', models.IntegerField(default=50, help_text='Intentos para Staff (Psicología/Coord) para análisis institucional.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Fecha en que el periodo fue cerrado institucionalmente', null=True)),
            ],
            options={
                'verbose_name': 'Periodo Académico (Governance)',
                'verbose_name_plural': 'Periodos Académicos (Governance)',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rol_usado', models.CharField(choices=[('DOCENTE', 'DOCENTE'), ('ESTUDIANTE', 'ESTUDIANTE'), ('ACUDIENTE', 'ACUDIENTE'), ('STAFF', 'STAFF'), ('ADMINISTRADOR', 'ADMINISTRADOR')], help_text='El rol con el que el usuario firmó la petición (Docente, Estudiante, etc).', max_length=50)),
                ('accion', models.CharField(choices=[('mejoras_estudiante', 'mejoras_estudiante'), ('orientacion_curso', 'orientacion_curso'), ('chat_socratico', 'chat_socratico'), ('analisis_convivencia', 'analisis_convivencia'), ('cumplimiento_pei', 'cumplimiento_pei')], help_text='La intención pedagógica (Intents).', max_length=50)),
                ('modelo_utilizado', models.CharField(default='deepseek-chat', max_length=50)),
                ('tokens_entrada', models.IntegerField(default=0, help_text='Contexto + Prompt (Lo que enviamos)')),
                ('tokens_salida', models.IntegerField(default=0, help_text='Respuesta generada (Lo que recibimos)')),
                ('tiempo_ejecucion', models.FloatField(default=0.0, help_text='Segundos que tardó la respuesta')),
                ('exitoso', models.BooleanField(default=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Si falló, aquí guardamos el stacktrace o mensaje de error de la API.', null=True)),
                ('metadata_tecnica', models.JSONField(blank=True, default=dict, help_text='Datalles técnicos: pei_version, razon_fallo, intentos_restantes, costo_estimado_usd.')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(help_text='Periodo académico activo durante la consulta.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.periodoacademico')),
            ],
            options={
                'verbose_name': 'Log de Uso IA',
                'verbose_name_plural': 'Auditoría de IA',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'periodo'], name='tasks_aiusa_usuario_00c5b6_idx'), models.Index(fields=['rol_usado', 'fecha'], name='tasks_aiusa_rol_usa_4fd858_idx')],
            },
        ),
    ]
