# Generated by Django 5.2 on 2025-12-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_peiresumen_periodoacademico_aiusagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Plan de Mejora - Matemáticas', max_length=200)),
                ('tipo', models.CharField(choices=[('reporte_pedagogico', 'Reporte Pedagógico Docente'), ('orientacion_estudiante', 'Plan de Mejora Estudiantil'), ('orientacion_acudiente', 'Orientación Familiar'), ('reporte_convivencia', 'Reporte de Convivencia'), ('reporte_institucional', 'Análisis Institucional (PEI)')], max_length=50)),
                ('contenido', models.TextField(help_text='Respuesta oficial de la IA en Markdown.')),
                ('contexto_snapshot', models.JSONField(blank=True, default=dict, help_text='\n        FOTO EXACTA de los datos usados (Notas, Observaciones) al momento de generar.\n        Sirve como evidencia inmutable.\n        ')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('es_publico', models.BooleanField(default=True, help_text='Si es True, acudientes o directores pueden verlo.')),
                ('log_origen', models.OneToOneField(blank=True, help_text='Enlace al log técnico que generó este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.aiusagelog')),
                ('pei_version', models.ForeignKey(help_text='Bajo qué versión del PEI se generó este documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.peiresumen')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.periodoacademico', verbose_name='Periodo Académico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_ia', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del Documento')),
            ],
            options={
                'verbose_name': 'Documento IA Oficial',
                'verbose_name_plural': 'Documentos IA Oficiales',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'tipo', 'periodo'], name='tasks_aidoc_usuario_a70ccc_idx')],
            },
        ),
    ]
