# Generated by Django 5.2 on 2025-12-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_aidocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='accion',
            field=models.CharField(choices=[('mejoras_estudiante', 'mejoras_estudiante'), ('chat_socratico', 'chat_socratico'), ('mejoras_docente', 'mejoras_docente'), ('orientacion_curso', 'orientacion_curso'), ('apoyo_acudiente', 'apoyo_acudiente'), ('staff_academico', 'staff_academico'), ('analisis_convivencia', 'analisis_convivencia'), ('cumplimiento_pei', 'cumplimiento_pei')], help_text='La intención pedagógica (Intents).', max_length=50),
        ),
    ]
