"""
    Django settings for djangocrud project.

    Generated by 'django-admin startproject' using Django 5.2.

    For more information on this file, see
    https://docs.djangoproject.com/en/5.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config 

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g)e7^67qy$r*nsd+0iy!-vl=k1a9sgg3+!(wddt)h(j^r1j6%p'

    # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


    # Application definition
INSTALLED_APPS = [
        # ⚡ Channels debe estar al principio para manejar runserver correctamente
        'channels',
        
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        
        # 🛠️ Utilidades de Frontend (Necesario para fechas amigables en el Feed)
        'django.contrib.humanize', 

        'tasks.apps.TasksConfig',
        'widget_tweaks',
    ]

MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        "whitenoise.middleware.WhiteNoiseMiddleware",
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        # Middleware for forcing password changes
        'tasks.middleware.ForcePasswordChangeMiddleware',
        # 🛡️ Middleware de Auditoría y Seguridad (Paso 10)
        'tasks.middleware.AuditMiddleware',
    ]

ROOT_URLCONF = 'djangocrud.urls'

TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR, 'templates'), # Global templates
                os.path.join(BASE_DIR, 'tasks', 'templates'), # Tasks app templates
            ],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    'django.template.context_processors.media', 
                    'tasks.context_processors.datos_globales_usuario', 
                ],
            },
        },
    ]

    # Servidor WSGI (Tradicional)
WSGI_APPLICATION = 'djangocrud.wsgi.application'

    # ===================================================================
    # ⚡ FASE III (PASO 11): CONFIGURACIÓN ASGI Y CHANNELS
    # ===================================================================

    # Servidor ASGI (Asíncrono para WebSockets)
ASGI_APPLICATION = 'djangocrud.asgi.application'

    # Configuración de Capas de Canales (Channel Layers)
CHANNEL_LAYERS = {
        "default": {
            # Usamos InMemory para desarrollo local (no requiere Redis instalado)
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
    # ===================================================================


    # Database
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default=''),
            'USER': config('DB_USER', default=''),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default=''),
            'PORT': config('DB_PORT', default=''),
        }
    }

    # High security password hashers (Argon2)
PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
        'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    ]

    # Password validation
    # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            'OPTIONS': {
                'min_length': 8,
            }
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

    # Authentication paths
LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/'

    # ===================================================================
    # 🩺 CONFIGURACIÓN DE ARCHIVOS MEDIA (PDFs, PEI, etc.)
    # ===================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    # ===================================================================
    # 🩺 FIN DE CONFIGURACIÓN MEDIA
    # ===================================================================

DEFAULT_TEMP_PASSWORD = '123456'


    # ==============================================================
    # CONFIGURACIÓN DE INTELIGENCIA ARTIFICIAL (Fase 4)
    # ==============================================================
    # Dejamos tu llave tal cual la tenías (Hardcoded)
DEEPSEEK_API_KEY = "sk-f4b636146a9147feb7c4e73e6e24d8f3"
AI_MODEL_NAME = "deepseek-chat"


    # --- CONFIGURACIÓN PARA RAILWAY ---

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    # 🔧 FIX CRÍTICO PARA RAILWAY (NO cast=bool)
if config('RAILWAY_ENVIRONMENT', default='') != '':
        DEBUG = False
        ALLOWED_HOSTS = ['*']
        CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']
else:
        DEBUG = True
        ALLOWED_HOSTS = ['*']

DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
        DATABASES = {
            'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=1800)
        }

REDIS_URL = config('REDIS_URL', default=None)
if REDIS_URL:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [REDIS_URL],
                },
            },
        }
else:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer"
            }
        }

CSRF_TRUSTED_ORIGINS = [
        "https://web-production-707fc.up.railway.app",
    ]

# settings.py

# ... Agrega esto al final si no existe, o añade las líneas con 'T' ...
DATETIME_INPUT_FORMATS = [
    '%Y-%m-%dT%H:%M:%S',    # Formato ISO (con T)
    '%Y-%m-%dT%H:%M',       # Formato ISO corto (con T)
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d %H:%M:%S.%f',
    '%Y-%m-%d %H:%M',
    '%m/%d/%Y %H:%M:%S',
]